minimumReleaseAgeExclude:
  - '@voidzero-dev/*'
  - vite-plus
  - '@vitest/*'
  - undici
overrides:
  vite@*: 'catalog:'
  vitest@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.cb0c4d234664905a9822ad2c197e482b59f763ac
  vitest: 5.0.1
  vite-plus: 0.0.0-commit.cb0c4d234664905a9822ad2c197e482b59f763ac
  '@vitest/coverage-v8': 5.0.1
