export default {
    kSocketId: Symbol('socket id'),
    kSocketStartTime: Symbol('socket start time'),
    kSocketConnectedTime: Symbol('socket connected time'),
    kSocketRequestEndTime: Symbol('socket request end time'),
    kSocketLocalAddress: Symbol('socket local address'),
    kSocketLocalPort: Symbol('socket local port'),
    kHandledRequests: Symbol('handled requests per socket'),
    kHandledResponses: Symbol('handled responses per socket'),
    kRequestSocket: Symbol('request on the socket'),
    kRequestId: Symbol('request id'),
    kRequestStartTime: Symbol('request start time'),
    kEnableRequestTiming: Symbol('enable request timing or not'),
    kRequestTiming: Symbol('request timing'),
    kRequestOriginalOpaque: Symbol('request original opaque'),
};
