name: CodSpeed

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@ddfb3df0429bb94a8a5db947f23a39518d6e6220 # main
        with:
          node-version: '24'
          cache: true

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v5
        with:
          mode: simulation
          run: vp test bench --run
