name: Publish Any Commit
on: [push, pull_request]

jobs:
  build:
    concurrency:
      group: pkg-pr-new-${{ github.workflow }}-#${{ github.event.pull_request.number || github.head_ref || github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@ea4ba6cb0e56b20656c4dc048fd0739a9ca2de09 # main
        with:
          node-version: 24
          cache: true
          sfw: true

      - name: Build
        run: vp run build

      - run: vp dlx pkg-pr-new publish
