name: Publish Any Commit
on: [push, pull_request]

jobs:
  build:
    concurrency:
      group: pkg-pr-new-${{ github.workflow }}-#${{ github.event.pull_request.number || github.head_ref || github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@b6a100fe28076884691ad8f750d6601635fc1e2a # pr/72
        with:
          node-version: 22
          cache: true
          run-install: true
          sfw: true

      - name: Build
        run: vp run build

      - run: vp dlx pkg-pr-new publish
